apiVersion: apps/v1
kind: Deployment
metadata:
  name: saifi36-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: saifi36
  template:
    metadata:
      labels:
        app: saifi36
    spec:
      containers:
      - name: saifi36
        image: saifi36/project:latest
        ports:
        - containerPort: 80
