apiVersion: v1
kind: Service
metadata:
  name: saifi36-service
  namespace: default  # Change as needed
spec:
  selector:
    app: saifi36
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  # Must match the container port
      nodePort: 32000   # NodePort in the range 30000-32767
  type: NodePort
